### ISSUE TITLE
Missing Required Module

### ISSUE THREAD

**Issue by ritheshSalyan** [zoho/LensCustomerSDK#1]
Hello,

When running provided example project we get **`Missing required modules: 'Reachability', 'SnapKit'`**. How to Resolve this issue

![Screenshot 2023-01-19 at 8 41 35 PM](https://user-images.githubusercontent.com/44966372/213479093-e5b4315d-66d0-41fe-8425-e7db1085fa4f.png)

**Comment by selvapandian-n-6155** [comment]
Hi Rithesh,

We've updated the SDK(2.4.1). Please check it now.
